### ISSUE TITLE
Navbar logo image background colour

### ISSUE THREAD

**Issue by kulasinghet** [kulasinghet/MedEx#78]
In the nav bar, the logo image looks like the background color is different from the rest of the others. Please fix that @D-Naveenz 

![image](https://user-images.githubusercontent.com/80462586/210752324-e0ed3778-88a4-4920-87f9-d8da804cd7d4.png)

**Comment by D-Naveenz** [comment]
I've designed it to look like a shade that is generated from overlapping the navbar and sidebar (a row and column. like the style of a table) It'll look better when the dashboard is completed. It's not a bug!
